### ISSUE TITLE
data entry suggestion

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#4]
just a thought, after testing the data entry screens. A simpler interface could have just one 'capture observation' button. Then all the options for how to define or choose a site (list, map, coords) are made available on the one form.

One possible issue with having multiple buttons is that you might fill in a form and then realise you need to choose another form instead - then what happens to what you've already entered?

**Comment by sokolic** [comment]
In the meeting I had with GroundTruth in April I showed them different options for initiating the observation input. One option was a drop-down menu which, when clicked, presented the three different input options. They preferred the present setup with multiple buttons. I agree that your proposal results in a cleaner interface but if we implement it we'd have to rethink the way the toggle buttons are handled. The two buttons on the LHS are toggle buttons so need to be visible so that the user can toggle them on or off.

**Comment by sokolic** [comment]
Regarding the issue with having to choose another form instead, the Close button on the form closes the form but retains any information that has already been entered. The form can then be reopened and the information will still be there. If the user choose a different input method, e.g. select from site list, then the logic assumes they are making a new observation and clears any previously entered information. Do you think we should modify this workflow?

**Comment by gubuntu** [comment]
GT should probably decide that. I was just trying all options fairly randomly, not necessarily like a real user would.
