### ISSUE TITLE
In Django Admin, allow observations to be sorted/filtered by flag value

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#62]

**Comment by rischanlab** [comment]
Hi @gubuntu after stuck and spend most of my time, because I cant show this page. I've succeeded to show the observations data in admin page. But I think this ticket has been done before. 

Please see the image below, the filtered by flag value has been supported in the observations page.

![screen shot 2015-10-23 at 5 02 53 pm](https://cloud.githubusercontent.com/assets/2235894/10690042/6c23271c-79a9-11e5-8dc0-736adc213c71.png)

**Comment by gubuntu** [comment]
you're right, this is already in place. I'll point it out to the client, not sure why they hadn't noticed it.
