### ISSUE TITLE
UI Suggestion: After clicking save and closing dialog box, close the form and clear the data

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#622]
After user uploads their record, a pop up is sent notifying them that they have successfully saved their record 
![image](https://github.com/kartoza/miniSASS/assets/90245715/4bc13157-f008-4a02-a629-0672d8ff38ad)

However, after clicking OK, the same data is still displayed:
![image](https://github.com/kartoza/miniSASS/assets/90245715/6696515d-978c-4924-a2ed-cd9be4a7aa4a)

I can continue clicking save numerous amount of time and it will create the exact record each time:
![image](https://github.com/kartoza/miniSASS/assets/90245715/b7f45370-385b-447b-bf78-9ff007b5cba6)

To prevent users from unintentionally uploading the same data over and over again, please clear the input and close the form after user clicks on OK on this pop up
![image](https://github.com/kartoza/miniSASS/assets/90245715/4bc13157-f008-4a02-a629-0672d8ff38ad)

**Comment by NyakudyaA** [comment]
You sometimes want to keep adding data to the same site but on different dates. I think a better check would be to disable the save button and reactivate it again if any of the inputs have been adjusted i.e Observation Date

If you have selected create site, that info should be added once into the DB and then it should automatically become an existing site , so it should not be saved again

**Comment by LunaAsefaw** [comment]
@NyakudyaA I agree, I was initially thinking of that but was not sure if we are allowed to have the same record again. Let's say I found a crab in the morning on site A then find another crab in the afternoon on the same site, since we only take date, do we pick up new records based on all the data being unique together (so water quality, ph etc too)?

**Comment by NyakudyaA** [comment]
@LunaAsefaw in theory it can happen but practically would a user measure all the other elements just because it's now afternoon, I doubt. Maybe the only thing that could change would be him taking more pics maybe cz the water was not clear in the morning. This would be a need for update observation provided you are the owner but in most cases we just have to go with one observation per day on a site. Obviously if you change the date we then should clear things like measurements /images etc
