### ISSUE TITLE
upgrade or replace ExtJS and GeoExtJS

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#88]
current front-end components include:
- ExtJS
- GeoExt
- OpenLayers (#104)

upgrade or swap these out for recent versions or frameworks that
1. are compatiable with the rest of the stack as upgraded
2. meet the original and current functional and UI/UX requirements

**Comment by sokolic** [comment]
OpenLayers release 2.12 is currently deployed whereas the current release version is 6.14. There have been major  changes to OpenLayers since 2.12 so much of the JavaScript code in minisass.js and minisass_map.js will need to be rewritten. Will need to check whether GeoExt will work with the latest release of OpenLayers.

**Comment by sokolic** [comment]
The latest version of GeoExt is 3.3.2 is built atop OpenLayers 4.6.5 and ExtJS 6.2.0. The current release of OpenLayers is 6.14 while Ext JS is at 7.51. Will need to check whether the older versions of OpenLayers and Ext JS need to be installed in order for GeoExt to work.

**Comment by sokolic** [comment]
Sencha have changed the licensing conditions of Ext JS since miniSASS was originally developed. Ext JS is released under the GNU General Public License version 3 (GPL v3) but their policy for Ext JS is that only major releases, such as 6.0, 7.0, and the first minor release immediately following a major release, such as 7.0.1, are available under GPL v3. All other releases, such as 6.2 and 6.2.1, are available to commercial license customers with current maintenance and support agreements. This could pose a problem with GeoExt.

**Comment by sokolic** [comment]
We could also consider removing GeoExt altogether as the current website uses virtually no GeoExt components. As far as I can see, only GeoExt.MapPanel is used.

**Comment by NyakudyaA** [comment]
Moved to new architecture
