### ISSUE TITLE
change basemaps

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#93]
The site uses a GroundTruth Google API key for Google Maps and occasionally they are charged a small amount that they are happy to continue. 

So keep Google but add one or two others such as OSM

**Comment by NyakudyaA** [comment]
Examples we could use:
```
 OpenStreetMap:
        URL: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    OpenStreetMap H.O.T:

    http://tile.openstreetmap.fr/hot/{z}/{x}/{y}.png


    CartoDB:
        URL: https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png

    Stamen:
        Stamen Toner: http://tile.stamen.com/toner/{z}/{x}/{y}.png
        Stamen Watercolor: http://tile.stamen.com/watercolor/{z}/{x}/{y}.png

    Thunderforest:
        Thunderforest OpenCycleMap: https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png
        Thunderforest Landscape: https://tile.thunderforest.com/landscape/{z}/{x}/{y}.png

    Esri ArcGIS Online:
        World Street Map: https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}
        World Imagery: https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
```
We also have rivers and catchments fixed to the bounds of SA, should we continue with this or remove it since we are not focusing on SA only? 
![image](https://github.com/kartoza/miniSASS/assets/2510900/84348872-ed7a-4483-a7e3-25c190a0a915)

An alternative would be to keep it and have logic only to make this available when we are showing SA
@amyburness what are your thoughts

**Comment by NyakudyaA** [comment]
Since the switch to Maplibre we using Satellite and OSM
